### ISSUE TITLE
[Bug]: 关于标签屏蔽无法正常生效

### ISSUE THREAD

**Issue by littlei** [Pacalini/PicaComic#1]
### 描述/Description

EH和JM的标签无法正常识别（？）.导致提取不到关键标签而没法进行屏蔽操作

### Version

4.0.4

### 使用的操作系统/Operating system

Android

**Comment by littlei** [comment]
识别标签的力度（准确度）不够.有的都识别不上

**Comment by Pacalini** [comment]
EH 我这边测试正常。
JM 现在似乎没办法在列表视图中拿到全部 tag 然后做屏蔽（参考官网），除非并发请求所有画廊的详情页并解密。
欢迎指正。

**Comment by littlei** [comment]
> ~EH 我这边测试正常。~ JM 现在似乎没办法在列表视图中拿到全部 tag 然后做屏蔽（参考官网），除非并发请求所有画廊的详情页并解密。 欢迎指正。

我一把hosts一关EH的标签也能读到了(绷)

**Comment by littlei** [comment]
> > > ~EH 我这边测试正常。~ JM 现在似乎没办法在列表视图中拿到全部 tag 然后做屏蔽（参考官网），除非并发请求所有画廊的详情页并解密。 欢迎指正。
> > 
> > 
> > 我一把hosts一关EH的标签也能读到了(绷)
> 
> 不对不是hosts的问题.是里站有问题，一选里站就读不到了

这下又觉得是网络出问题了

**Comment by littlei** [comment]
> > > > ~EH 我这边测试正常。~ JM 现在似乎没办法在列表视图中拿到全部 tag 然后做屏蔽（参考官网），除非并发请求所有画廊的详情页并解密。 欢迎指正。
> > > 
> > > 
> > > 我一把hosts一关EH的标签也能读到了(绷)
> > 
> > 
> > 不对不是hosts的问题.是里站有问题，一选里站就读不到了
> 
> 这下又觉得是网络出问题了

网络会导致识别不到EH的标签(？)

**Comment by Pacalini** [comment]
测试下最新 commit，或者等 release
