### ISSUE TITLE
[Bug]: Picacg本地收藏无法正常取消

### ISSUE THREAD

**Issue by kvjtod** [Pacalini/PicaComic#13]
### 描述/Description

Picacg的本地收藏不能通过按钮取消，只能手动在文件夹中删除，bug与nhentai本地收藏无法取消类似

### Version

4.1.2

### 使用的操作系统/Operating system

Android

**Comment by Pacalini** [comment]
无法复现。录屏看看？

**Comment by kvjtod** [comment]
> 无法复现。录屏看看？

不太清楚触发的条件，大部分时候都无法复现，有的时候随便点点就能复现...

https://github.com/user-attachments/assets/6a204872-152c-4dc6-92a9-f14f9d88aeaa

在16秒的时候成功复现了一次
