### ISSUE TITLE
[Bug]: e站看不了图片

### ISSUE THREAD

**Issue by Ponezun** [Pacalini/PicaComic#15]
### 描述/Description

貌似是e站更新了图片相关东西导致的

### Version

4.1.2

### 使用的操作系统/Operating system

Android

### 日志/logs

IntegerDivisionByZeroException
#0      EhNetwork.getReaderLink (package:pica_comic/network/eh_network/eh_main_network.dart)
<asynchronous suspension>
#1      ImageManager.getEhImageNew (package:pica_comic/foundation/image_manager.dart:185)
<asynchronous suspension>
#2      ReadingData.loadImage (package:pica_comic/pages/reader/reading_data.dart:57)
<asynchronous suspension>
#3      StreamImageProvider.load (package:pica_comic/foundation/image_loader/stream_image_provider.dart:29)
<asynchronous suspension>
#4      BaseImageProvider._loadBufferAsync (package:pica_comic/foundation/image_loader/base_image_provider.dart:53)
<asynchronous suspension>
#5      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:1013)
<asynchronous suspension>

**Comment by Pacalini** [comment]
先暂时切回表站，周末修复
