### ISSUE TITLE
[Bug]: 预览图错位, 打开后看到的是再往前十几张的图

### ISSUE THREAD

**Issue by ShiinaManatsu** [Pacalini/PicaComic#16]
### 描述/Description

如视频描述

https://github.com/user-attachments/assets/5a2f2a77-072c-444a-8408-f00327fbaf39

### Version

4.1.2

### 使用的操作系统/Operating system

Windows

**Comment by Pacalini** [comment]
用的 e-hentai.org 还是 exhentai.org ？
所有漫画都错位吗？

**Comment by ShiinaManatsu** [comment]
> 用的 e-hentai.org 还是 exhentai.org ？ 所有漫画都错位吗？

你好, eh和ex都会, 所有的都会, 试了下从第21个开始错位一个, 看起来像是有被吞掉的图, 266P变成了252结束
![image](https://github.com/user-attachments/assets/93a43ee4-9170-47a8-b596-c6126d6d6ec9)

![image](https://github.com/user-attachments/assets/c86b7370-21b8-4f03-9c1d-c9e248deb1b2)

## 视频:
https://github.com/user-attachments/assets/aa6c942d-9edb-4dd7-b2a2-6515898a030d

--------
又开了一个这次变多了..

![image](https://github.com/user-attachments/assets/0bed8458-3fb8-4b43-91f4-03ba9fd91dc1)
![image](https://github.com/user-attachments/assets/69ae706b-6417-433d-ad34-31b70e3cdf90)

**Comment by Pacalini** [comment]
清下缓存，试下新版本

**Comment by ShiinaManatsu** [comment]
> 清下缓存，试下新版本

试了下4.1.3, 加载不出preview了, 回到4.1.2正常, 当然4.1.2清缓存也是错位的

![image](https://github.com/user-attachments/assets/5535f608-fdcf-4160-a448-05964225643e)

**Comment by Pacalini** [comment]
怪了，ex 昨天更新之后 4.1.2 应该看不了了，4.1.3 修完才正常，跟你反过来。
无法复现，先等其他人反馈。
