### ISSUE TITLE
[Enhancement]: 允许调用外部上色接口

### ISSUE THREAD

**Issue by Shapaper233** [Pacalini/PicaComic#17]
### 描述/Description

我手头上有几个测试还不错的上色AI模型。
现在假如想要把黑白图片转换为彩色的话需要下载到磁盘后上色完手动替换。
我在想能不能提供一个“图片转换API”设置，将从漫画源下载的图片先通过POST发送给这个API（或者调用命令行）。转换完成后返回彩图后再显示。（Tips：建议加个缓存，上色步骤大概率消耗不少。）【下载漫画的地方也可以加复选框询问是否上色】

可以先实现这个功能，给出API规范后由用户自行实现！

**Comment by Pacalini** [comment]
欢迎 PR。
