### ISSUE TITLE
支持hosts一个域名对应多个IP地址，以防一个IP失效而无法直连

### ISSUE THREAD

**Issue by nief12** [Pacalini/PicaComic#18]
### 描述/Description

像Ehviewer_CN SXJ，可以一个域名多个ip地址，其代码地址是https://github.com/xiaojieonly/Ehviewer_CN_SXJ/blob/BiLi_PC_Gamer/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fhippo%2Fehviewer%2Fclient%2FEhHosts.java     我以前都是IP失效了在这找的有效的IP，但最近因为失效或卡顿特别频繁，要是能支持这个功能，就不用一个一个IP地来试了

### 操作系统/Operating System

Android

**Comment by Pacalini** [comment]
网络问题请自行解决，host 等功能将来不再维护。
