### ISSUE TITLE
[Bug]: ex画廊出现Null check operator used on a null value

### ISSUE THREAD

**Issue by S-T-eve** [Pacalini/PicaComic#20]
### 描述/Description

使用exhentai画廊报Null check operator used on a null value，e-hentai画廊无此问题

### Version

v4.1.3-arm64-v8a

### 使用的操作系统/Operating system

Android

### 日志/logs

Null check operator used on a null value
#0      EhNetwork.getGalleryInfo.<anonymous closure> (package:pica_comic/network/eh_network/eh_main_network.dart:624)
#1      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:354)
#3      List.addAll (dart:core-patch/growable_array.dart:320)
#4      EhNetwork.getGalleryInfo (package:pica_comic/network/eh_network/eh_main_network.dart:621)
<asynchronous suspension>
#5      EhGalleryPage.loadData (package:pica_comic/pages/ehentai/eh_gallery_page.dart:67)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:534)
<asynchronous suspension>
#7      ComicPageLogic.get (package:pica_comic/pages/comic_page.dart:604)
<asynchronous suspension>

**Comment by Pacalini** [comment]
> Settings
Gallery Page Thumbnail Labeling 改成 None
