### ISSUE TITLE
ehentai预览图无法查看

### ISSUE THREAD

**Issue by kvjtod** [Pacalini/PicaComic#24]
### 描述/Description

ehentai预览图在漫画源选择为表站情况下仍然无法查看，在同ip下ehentai网页可正常加载预览图

### Version

4.1.3

### 使用的操作系统/Operating system

Android

### 截图或视频/Screenshot or video

![SmartSelect_20241031_154202](https://github.com/user-attachments/assets/504ab5d4-46b5-45d7-8a43-91816809a138)
![Screenshot_20241031_154224_Chrome](https://github.com/user-attachments/assets/73f7d999-1b30-49f3-b5d8-a471e84e0e04)

**Comment by Pacalini** [comment]
已修复，等更新
