### ISSUE TITLE
[Bug]: eh偶尔会出现卡死，后续都用不了

### ISSUE THREAD

**Issue by wdnmd9527529** [Pacalini/PicaComic#30]
### 描述/Description

Null check operator used on a null value

刷新，换网，清除缓存，乃至卸载重装只要导入收藏就没用

### Version

4.1.4

### 使用的操作系统/Operating system

Android

### 日志/logs

无

### 截图或视频/Screenshot or video

![issues](https://github.com/user-attachments/assets/128c1c24-a6e3-4e5b-900b-cb06bde99462)

**Comment by Pacalini** [comment]
更新试试
