### ISSUE TITLE
[Bug]: nhentai的漫画看不了

### ISSUE THREAD

**Issue by misaka18848** [Pacalini/PicaComic#31]
### 描述/Description

nhentai点进去有的漫画第二页起就看不了了，报错404notfound

### Version

4.1.6

### 使用的操作系统/Operating system

Android

**Comment by johnsonsleo** [comment]
+1

**Comment by tinker4673** [comment]
看样子是webp的问题

**Comment by Pacalini** [comment]
nhentai 网页某些缩略图链接依然有问题，等网站修复。
