### ISSUE TITLE
[Bug]: 哔咔无法登录

### ISSUE THREAD

**Issue by mx41shy** [Pacalini/PicaComic#32]
### 描述/Description

哔咔无法登录

### Version

4.1.6

### 使用的操作系统/Operating system

Windows

### 日志/logs

DioException [unknown]: null
Error: Invalid argument(s): No host specified in URI https:t4.wnimg.ru/data/t/2723/08/17298476817329.png
#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:510)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _FutureListener.handleError (dart:async/future_impl.dart:181)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:873)
#5      Future._propagateToListeners (dart:async/future_impl.dart:894)
#6      Future._completeError (dart:async/future_impl.dart:674)
#7      _SyncCompleter._completeError (dart:async/future_impl.dart:63)
#8      _Completer.completeError (dart:async/future_impl.dart:27)
#9      Future.any.onError (dart:async/future.dart:633)
#10     _rootRunBinary (dart:async/zone.dart:1423)
#11     _CustomZone.runBinary (dart:async/zone.dart:1315)
#12     _FutureListener.handleError (dart:async/future_impl.dart:178)
#13     Future._propagateToListeners.handleError (dart:async/future_impl.dart:873)
#14     Future._propagateToListeners (dart:async/future_impl.dart:894)
#15     Future._completeError (dart:async/future_impl.dart:674)
#16     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:760)
#17     _rootRun (dart:async/zone.dart:1399)
#18     _CustomZone.run (dart:async/zone.dart:1301)
#19     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

### 截图或视频/Screenshot or video

![image](https://github.com/user-attachments/assets/3abc1b60-7059-4568-a4f7-fc786292af92)

**Comment by Pacalini** [comment]
无法复现。提供一下报错前的日志（对 https://picaapi.picacomic.com/users/profile 的请求）

**Comment by mx41shy** [comment]
> 无法复现。提供一下报错前的日志（对 https://picaapi.picacomic.com/users/profile 的请求）

GET https://picaapi.picacomic.com/users/favourite?s=dd&page=1
DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
null
