### ISSUE TITLE
[Enhancement]: 建议关键词屏蔽和自动语言筛选在探索页面也起效

### ISSUE THREAD

**Issue by misaka18848** [Pacalini/PicaComic#33]
### 描述/Description

如题

### 操作系统/Operating System

Android

**Comment by Pacalini** [comment]
指的哪个漫画源？

**Comment by misaka18848** [comment]
nhentai

**Comment by Pacalini** [comment]
nhentai 探索页关键词屏蔽是生效的。
现在的语言筛选是搜索时由服务端进行的，无法在探索页添加。
