### ISSUE TITLE
[Bug]: 包子漫画无法完成cloudflare验证

### ISSUE THREAD

**Issue by youhupanda** [Pacalini/PicaComic#4]
### 描述/Description

打开包子漫画cf验证时闪退

### Version

4.1.0

### 使用的操作系统/Operating system

Android

### 日志/logs

Failed to load a image:
Url:https:t4.qy0.ru/data/t/2687/48/17273494671751.jpg
Error:DioException [unknown]: null
Error: Invalid argument(s): No host specified in URI https:t4.qy0.ru/data/t/2687/48/17273494671751.jpg

### 截图或视频/Screenshot or video

https://github.com/user-attachments/assets/22a5b1f8-3862-48bf-bc2a-195380dfb97b

**Comment by Pacalini** [comment]
无法复现
多点几下，再不行就是网络问题，自行解决
