### ISSUE TITLE
希望能增加本地漫画导入不覆盖的功能

### ISSUE THREAD

**Issue by tian1521** [Pacalini/PicaComic#40]
### Content

现在exhentai的归档下载没以前好用了，之前归档下载没配额后换路线就可以恢复归档下载。。。现在换路线没用了(눈_눈)下一两本很短的本子后，就限制不能下载，要等第二天才解除限制，如果能导入本地图片格式的漫画，且不覆盖原有的数据，就可以用机器人归档下载了，感谢_(:3」∠❀)_

**Comment by Pacalini** [comment]
外部归档下载的不包含 app 需要的画廊相关信息 无法导入。
