### ISSUE TITLE
[Bug]: nhentai图片无法加载

### ISSUE THREAD

**Issue by nickz416** [Pacalini/PicaComic#43]
### 描述/Description

![Screenshot_2024-11-15-07-38-45-38_ee5538e241632f3f2dcad110bc43c716](https://github.com/user-attachments/assets/05e5e1fb-ddf3-49f6-85af-0a760c208273)
nhentai所有漫画点进去都是显示invalid code 404 ，但是漫画各页的预览图可以正常看

### Version

4.1.6

### 使用的操作系统/Operating system

Android

### 截图或视频/Screenshot or video

![Screenshot_2024-11-15-07-38-45-38_ee5538e241632f3f2dcad110bc43c716](https://github.com/user-attachments/assets/f361690d-34bc-45a1-90b1-977353a15777)
![IMG_20241115_074248](https://github.com/user-attachments/assets/251f7788-554d-4093-b3b3-4c132a19eb13)

**Comment by ktwzt** [comment]
我也是这个问题，卸载重装也不行

**Comment by Pacalini** [comment]
Duplicate of #31
