### ISSUE TITLE
[Bug]: exhentai本子页缩略图无法加载

### ISSUE THREAD

**Issue by Azusa-mikan** [Pacalini/PicaComic#52]
### 描述/Description

缩略图看到第20页以后全部无法加载，手机也是如此

### Version

4.1.7

### 使用的操作系统/Operating system

Android, Windows

### 日志/logs

[logs.txt](https://github.com/user-attachments/files/17841252/logs.txt)

### 截图或视频/Screenshot or video

![image](https://github.com/user-attachments/assets/f23036c9-004e-475a-8fbf-a93fdc0034bb)

**Comment by Azusa-mikan** [comment]
补充：阅读正常

**Comment by Pacalini** [comment]
600daa3
