### ISSUE TITLE
[Bug]: 已下载漫画无法导出pdf

### ISSUE THREAD

**Issue by nihhhty** [Pacalini/PicaComic#6]
### 描述/Description

已下载漫画无法导出pdf,软件里输出日志未字体下载链接404

### Version

4.1.1

### 使用的操作系统/Operating system

iOS

### 日志/logs

GET https://raw.githubusercontent.com/wgh136/PicaComic/dev/fonts/NotoSansSC-Regular.ttf
DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

Instance of 'ResponseBody'

**Comment by 096huayang** [comment]
你好，你好，现在还是不能导出pdf，还是提示缺少字体文件，然后就是下载失败
![Uploading IMG_20241015_191209.jpg…]()

**Comment by 096huayang** [comment]
你好，现在下载的漫画还是不能导出为pdf，还是提示缺少字体文件，然后下载失败
![IMG_20241015_191209](https://github.com/user-attachments/assets/628effae-78e8-4c6d-bb11-2b159d22a2cc)

**Comment by Pacalini** [comment]
> 你好，现在下载的漫画还是不能导出为pdf，还是提示缺少字体文件，然后下载失败 ![IMG_20241015_191209](https://private-user-images.githubusercontent.com/103228362/376584267-628effae-78e8-4c6d-bb11-2b159d22a2cc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5OTE2MTksIm5iZiI6MTcyODk5MTMxOSwicGF0aCI6Ii8xMDMyMjgzNjIvMzc2NTg0MjY3LTYyOGVmZmFlLTc4ZTgtNGM2ZC1iYjExLTJiMTU5ZDIyYTJjYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxMTIxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTZiZjBlNjc3MjBkMTFlZmEwYzM5OTUwM2RkYTg0ODRhMGJlNzc3MmFjOWU0MGE0NGY3ZTBhNGY1ZWNlNmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mDwN1NpeMLRHerGQbj4m4FXZSf8B78j6FT9vM0Pa39Q)

已修复，等下个 release
