### ISSUE TITLE
[Bug]: nhentai看最近新的漫画提示404 not found，以前的漫画正常

### ISSUE THREAD

**Issue by misaka18848** [Pacalini/PicaComic#61]
### 描述/Description

如题

### Version

4.2.0

### 使用的操作系统/Operating system

Android

### 截图或视频/Screenshot or video

![Screenshot_2024-12-08-12-18-41-424_com github pacalini pica_comic](https://github.com/user-attachments/assets/e5721e13-1b26-4605-a856-b5718bfd82e2)

**Comment by Pacalini** [comment]
Duplicate of #60
