### ISSUE TITLE
数据同步打开app后后台同步，不在界面弹窗提示

### ISSUE THREAD

**Issue by nief12** [Pacalini/PicaComic#62]
![Screenshot_20241208_214955.jpg](https://github.com/user-attachments/assets/3d5bdf64-51cc-41b2-bf95-1ad3b2297894)

如果经常多端使用像venera这样就很优雅，不会太别扭

**Comment by Pacalini** [comment]
~~所以为什么不直接用 venera~~

**Comment by nief12** [comment]
> ~~所以为什么不直接用 venera~~

因为他没有hosts功能，不想要多余的打开科学上网。。

**Comment by nief12** [comment]
> ~~所以为什么不直接用 venera~~

你要是想裸上nhentai可以用这个        "nhentai.net": "104.27.206.92",
        "static.nhentai.net": "104.27.206.92",
        "t7.nhentai.net": "104.27.206.92",
        "t3.nhentai.net": "104.27.206.92",
        "t5.nhentai.net": "104.27.206.92",
        "i3.nhentai.net": "104.27.206.92",
        "i5.nhentai.net": "104.27.206.92",
        "i7.nhentai.net": "104.27.206.92",
绅士漫画你在设置里换一下网页地址就OK了，只是本来可以直接打开软件就能用，还要多点一步就很鸡贼。。
