### ISSUE TITLE
[Enhancement]跨页内容临时单页显示

### ISSUE THREAD

**Issue by Q16KBreak** [Pacalini/PicaComic#67]
### Content

非常感谢作者能开发出这么好的软件，希望可以添加一个小功能，在阅读模式“双页(反向)”识别跨页内容并临时单页显示。
![exp](https://github.com/user-attachments/assets/40fd3493-88f4-477a-b019-77c136d8de3e)
如图所示 有的漫画源会将A+B这种跨页内容合并为单张图片
目前观看流程为 手动放大- 打开设置 - 切换“首页显示单张图片” 非常麻烦
希望可以添加开关来识别 长>宽为单页显示 长<=宽继续维持双页显示

**Comment by Pacalini** [comment]
阅读器和阅读模式相关的代码 我一个人改起来比较困难
可以试试原作者新的 [venera](https://github.com/venera-app/venera)，开发者比较多，有问题去那里提。

**Comment by Q16KBreak** [comment]
> 阅读器和阅读模式相关的代码 我一个人改起来比较困难 可以试试原作者新的 [venera](https://github.com/venera-app/venera)，开发者比较多，有问题去那里提。

感谢指路！小用了一段时间发现逻辑和此软件有很大不同 我先深度用一段时间再提吧
