### ISSUE TITLE
[Bug]: BUG以及建议

### ISSUE THREAD

**Issue by xoevdv** [Pacalini/PicaComic#8]
### 描述/Description

用软件发现的BUG以及一些建议，希望大佬可以看看
1：用漫画源哔咔，搜索时不会记录搜索历史，其它源是正常的
2：绅士漫画网络收藏夹无法在APP内实现，希望大佬可以看看能不能在APP内也可以取消

### Version

最新

### 使用的操作系统/Operating system

Android

**Comment by Pacalini** [comment]
1：[d58dad2](https://github.com/Pacalini/PicaComic/commit/d58dad27667ff33198ce70983491b954f5654b15) 已修复
2：现在注册未开放，我不知道能否实现、如何实现，只能放着等有缘人了。

**Comment by xoevdv** [comment]
> 1：[d58dad2](https://github.com/Pacalini/PicaComic/commit/d58dad27667ff33198ce70983491b954f5654b15) 已修复 2：现在注册未开放，我不知道能否实现、如何实现，只能放着等有缘人了。

好的，感谢
